### ISSUE TITLE
test issue on github

### ISSUE THREAD

**Issue by oharac** [oharac/esm514_equity#1]
Everyone should now be added to this project as collaborators.  We can use Github issues to track our ideas and work, all in one space, searchable and able to reply by email.  It's way better than trying to keep track of random e-mail chains.  

Later when we get into producing code and data we can use Github to store our stuff too.

**Comment by elliottfinn** [comment]
Hey friends!!!

**Comment by oharac** [comment]
kjn ipcfa;j;y; cb;ibhk

**Comment by oharac** [comment]
We can also cross-reference issues by using the number sign/hashtag sign then the number that Github assigns to the issue (e.g. #1 refers to the first issue, "test issue on github")

And you can tag other people using the "at" symbol like Twitter: @elliottfinn @yangqiu91 @vthivierge @rachtorr
